### ISSUE TITLE
user identifier already exists

### ISSUE THREAD

**Issue by acareaga** [patwey/traffic_spy#4]
As a registered user

When I send a GET request to http://localhost:9393/sources

With the data - Identifier and rootUrl ('identifier=jumpstartlab&rootUrl=http://jumpstartlab.com')

AND the user already exists

I expect to see the RESPONSE of "Identifier Already Exists - 403 Forbidden"

**Comment by patwey** [comment]
U ROCK

**Comment by tjkomor** [comment]
need to refactor
